#bump
language: android
jdk: oraclejdk7
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

script:
    - cp gradle.properties.example gradle.properties
    - ./gradlew clean assembleDebug testDebug
    
